#!/bin/bash

for users in "$@"; do
    IFS=':' read -a data <<< "$users"
    user="${data[0]}"
    pass="${data[1]}"

    if [ "${data[2]}" == "e" ]; then
        chpasswdOptions="-e"
        uid="${data[3]}"
        gid="${data[4]}"
        hdir="${data[5]}"
    else
        uid="${data[2]}"
        gid="${data[3]}"
        hdir="${data[4]}"
    fi

    useraddOptions="--no-user-group"

    if [ -n "$uid" ]; then
        useraddOptions="$useraddOptions --non-unique --uid $uid"
    fi

    if [ -n "$gid" ]; then
        useraddOptions="$useraddOptions --gid $gid"
        groupadd --gid $gid $gid
    fi

    if [ -n "$hdir" ]; then
        useraddOptions="$useraddOptions --home $hdir"
    else
        useraddOptions="$useraddOptions --create-home"
    fi

    useradd $useraddOptions $user
    if [ -z "$hdir" ]; then
        chown root:root /home/$user
        chmod 755 /home/$user
    fi

    if [ -z "$pass" ]; then
        pass="$(echo `</dev/urandom tr -dc A-Za-z0-9 | head -c256`)"
        chpasswdOptions=""
    fi

    echo "$user:$pass" | chpasswd $chpasswdOptions

    if [ -z "$hdir" ]; then
      cat /home/$user/.ssh/keys/* >> /home/$user/.ssh/authorized_keys
      chown $user /home/$user/.ssh/authorized_keys
      chmod 600 /home/$user/.ssh/authorized_keys
    fi
done

exec /usr/sbin/sshd -D
