#!/bin/bash

set -xe

SFTP_USERS_FILE="/etc/sftp_users"

createUser() {
    user="$1"
    pass="$2"

    if [ "$3" == "e" ]; then
        chpasswdOptions="-e"
        uid="$4"
        gid="$5"
        hdir="$6"
    elif [ "$3" == "k" ]; then
        sshkey="true"
        uid="$4"
        gid="$5"
        hdir="$6"
    else
        uid="$3"
        gid="$4"
        hdir="$5"
    fi

    useraddOptions="--no-user-group"

    if [ -n "$uid" ]; then
        useraddOptions="$useraddOptions --non-unique --uid $uid"
    fi

    if [ -n "$gid" ]; then
        useraddOptions="$useraddOptions --gid $gid"
        groupadd --gid $gid $gid
    fi

    if [ -n "$hdir" ]; then
        useraddOptions="$useraddOptions --home $hdir"
    else
        useraddOptions="$useraddOptions --create-home"
    fi

    useradd $useraddOptions $user
    if [ -z "$hdir" ]; then
        chown root:root /home/$user
        chmod 755 /home/$user
    fi

    if [ -z "$pass" -o -n "$sshkey" ]; then
        passToSet="$(echo `</dev/urandom tr -dc A-Za-z0-9 | head -c256`)"
        chpasswdOptions=""
    else
        passToSet="$pass"
    fi

    if [ -n "$sshkey" ]; then
        authorized_keys_file="/home/$user/.ssh/authorized_keys"
        mkdir -p /home/$user/.ssh
        chown $uid:$gid /home/$user/.ssh
        chmod 700 /home/$user/.ssh
        if [ ! -e "$authorized_keys_file" -o -e "$authorized_keys_file" -a -z "$(grep "$pass" $authorized_keys_file)" ]; then
            echo "$pass" >> $authorized_keys_file
            chown $user $authorized_keys_file
            chmod 600 $authorized_keys_file
        fi
    fi

    echo "$user:$passToSet" | chpasswd $chpasswdOptions

    if [ -z "$hdir" -a -d "/home/$user/.ssh/keys" ]; then
      cat /home/$user/.ssh/keys/* >> /home/$user/.ssh/authorized_keys
      chown $user /home/$user/.ssh/authorized_keys
      chmod 600 /home/$user/.ssh/authorized_keys
    fi

    if [ -n "$STORAGE_DIR" ]; then
        mkdir -p "/home/$user/$STORAGE_DIR"
        chown $uid:$gid "/home/$user/$STORAGE_DIR"
        chmod 700 "/home/$user/$STORAGE_DIR"
    fi
}


if [ -e "$SFTP_USERS_FILE" ]; then
    while read line; do
        if [ -n "$line" ]; then
            IFS=':' read -a data <<< "$line"
            createUser "${data[0]}" "${data[1]}" "${data[2]}" "${data[3]}" "${data[4]}" "${data[5]}" "${data[6]}" 
        fi
    done <$SFTP_USERS_FILE
fi


usersSource="$@"

for users in "$usersSource"; do
    if [ -n "$users" ]; then
        IFS=':' read -a data <<< "$users"
        createUser "${data[0]}" "${data[1]}" "${data[2]}" "${data[3]}" "${data[4]}" "${data[5]}" "${data[6]}" 
    fi
done

exec /usr/sbin/sshd -D
